import './style.css';import {posts as baked} from './posts.js';
let posts=baked;
/* public demo posts (Supabase, demo rows only) with baked fallback */
const SB_URL="https://iljapbrjcxhtymtkiuea.supabase.co",SB_KEY="sb_publishable_bKtD9c5Q0GzMFNOZQ58z8A_WCIxbRt8";
let remoteOk=false;
async function loadRemote(){try{const r=await fetch(SB_URL+"/rest/v1/working_notes_posts?select=id,title,subtitle,date,kind,minutes,status,featured,paragraphs&order=featured.desc,created_at.asc",{headers:{apikey:SB_KEY}});if(!r.ok)throw 0;const rows=await r.json();if(!Array.isArray(rows)||!rows.length)throw 0;posts=rows;p=posts[0];remoteOk=true}catch(e){remoteOk=false}render()}
const app=document.getElementById('app');let query='';
let p=posts[0];const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const card=x=>`<a class="post-card ${x.paragraphs.length?'':'disabled-card'}" href="${x.paragraphs.length?'#essay/'+x.id:'#archive'}" ${x.paragraphs.length?'':'aria-disabled="true"'}><div class="post-card-top"><span>${safe(x.kind)}</span><span>${safe(x.date)}</span></div><div class="post-card-body"><h3>${safe(x.title)}</h3><p>${safe(x.subtitle)}</p></div><div class="post-card-bottom"><span>${safe(x.status)}</span><span>${x.paragraphs.length?'READ ↗':'NOT PUBLISHED YET'}</span></div></a>`;
function chrome(content){return `<div class="site"><header><a href="#home" class="wordmark" aria-label="Working Notes home">w<span>·</span>n<span class="wordmark-full"> / working notes</span></a><nav aria-label="Main navigation"><a href="#home" data-nav="home">Home</a><a href="#archive" data-nav="archive">Writing</a><a href="#about" data-nav="about">About</a></nav><span class="header-right">A PUBLIC NOTEBOOK, IN PROGRESS <span class="green-dot">●</span> <span class="wn-live">${remoteOk?'NOTEBOOK · LIVE':'OFFLINE · BAKED'}</span></span></header><main>${content}</main><footer><div><a class="foot-logo" href="#home">w<span>·</span>n</a><p>Thoughts from the messy middle of making things.</p></div><div class="footer-links"><a href="#archive">Writing ↗</a><a href="#about">About ↗</a><a href="https://github.com/Aditya2375" target="_blank" rel="noopener noreferrer">GitHub ↗</a></div><span>© 2026 WORKING NOTES</span></footer></div>`}
function home(){return chrome(`<section class="hero"><div class="issue-line"><span>NO. 001 / BUILD NOTES</span><span>WRITTEN IN PUBLIC</span></div><div class="hero-grid"><div><span class="overline">A LOG OF BUILDING THINGS, HONESTLY</span><h1>Working<br><em>notes</em><span class="period">.</span></h1></div><aside><div class="ornament" aria-hidden="true">↗</div><p>Somewhere between an idea and a finished product is the part worth writing down.</p><a href="#archive">Browse the writing <span>↗</span></a></aside></div><div class="hero-rule"><span>A BUILDER’S NOTEBOOK</span><span>FIRST-YEAR BUILDER / ISSUE 001</span><span>SCROLL TO READ ↓</span></div></section><section class="home-feature"><div class="eyebrow">01 / THE FIRST STORY</div><div class="feature-grid"><div><span class="feature-category">BUILD DIARY / 5 MIN READ</span><h2>Four days,<br><i>twenty-nine</i><br>versions.</h2></div><div class="feature-side"><div class="sketch" aria-hidden="true"><div class="sketch-num">29</div><span>ITERATIONS / ONE IDEA</span><div class="sketch-arrows">↖ <span>↗</span></div></div><p>On building a portfolio, stripping JavaScript out, and learning what a constraint can do.</p><a class="read-link" href="#essay/${p.id}">READ THE ESSAY <span>↗</span></a></div></div></section><section class="home-index"><div class="index-header"><div><span class="eyebrow">02 / THE WRITING DESK</span><h2>From the notebook.</h2></div><a href="#archive">VIEW THE ARCHIVE ↗</a></div><div class="post-grid">${posts.map(card).join('')}</div></section><section class="home-last"><div>✳</div><p>Make something.<br><em>Then make sense of it.</em></p><a href="#about">MORE ABOUT THIS NOTEBOOK ↗</a></section>`)}
function archive(){let found=posts.filter(x=>(x.title+' '+x.subtitle+' '+x.kind).toLowerCase().includes(query.toLowerCase()));return chrome(`<section class="archive-head"><span class="overline">THE ARCHIVE / ISSUE 001</span><h1>Written in<br>the <em>margins.</em></h1><p>A record of building, changing course, and noticing what works. One full essay so far; the rest are on the desk.</p><div class="archive-search"><label for="search">SEARCH THE NOTEBOOK</label><input id="search" type="search" placeholder="Try portfolio, constraints..." value="${safe(query)}" autocomplete="off"><span aria-hidden="true">⌕</span></div></section><section class="archive-list"><div class="archive-line"><span>ALL ENTRIES</span><span>${found.length} RESULT${found.length===1?'':'S'}</span></div>${found.length?found.map((x,i)=>`<a href="${x.paragraphs.length?'#essay/'+x.id:'#archive'}" class="archive-row ${x.paragraphs.length?'':'unpublished'}" ${x.paragraphs.length?'':'aria-disabled="true"'}><span class="row-n">0${i+1}</span><div><span class="row-type">${safe(x.kind)} / ${safe(x.status)}</span><h2>${safe(x.title)}</h2><p>${safe(x.subtitle)}</p></div><span class="archive-date">${safe(x.date)}<b>${x.paragraphs.length?'↗':'—'}</b></span></a>`).join(''):`<div class="no-results">Nothing in the notebook matches that yet.</div>`}</section>`)}
function article(){return chrome(`<div class="read-progress" id="read-progress"></div><article class="essay"><a href="#archive" class="back">← THE ARCHIVE</a><div class="essay-head"><span class="overline">01 / BUILD DIARY</span><h1>Four days,<br><em>twenty-nine</em><br>versions.</h1><p>${safe(p.subtitle)}</p><div class="essay-meta"><div><span>WORDS BY</span><strong>WORKING NOTES</strong></div><div><span>DATE</span><strong>${p.date}</strong></div><div><span>READ TIME</span><strong>${p.minutes} MIN</strong></div></div></div><div class="essay-paper"><div class="essay-margin"><span>WORKING NOTES<br>NO. 001</span><div class="margin-lines"></div><span>READ / REVISE / REPEAT</span></div><div class="essay-text">${p.paragraphs.map(block=>block.type==='lead'?`<p class="lead">${safe(block.text)}</p>`:block.type==='h'?`<h2>${safe(block.text)}</h2>`:block.type==='pull'?`<blockquote>“${safe(block.text)}”</blockquote>`:block.type==='end'?`<div class="essay-disclaimer"><span>BEFORE PUBLICATION</span><p>${safe(block.text)}</p></div>`:`<p>${safe(block.text)}</p>`).join('')}<div class="essay-bottom"><span>END / 001</span><a href="#archive">BACK TO THE ARCHIVE ↗</a></div></div></div></article>`)}
function about(){return chrome(`<section class="about-head"><span class="overline">ABOUT / WORKING NOTES</span><h1>A place to leave<br>the <em>working out.</em></h1><p>Good work rarely arrives fully formed. This notebook is for the drafts, detours, and decisions behind what gets made.</p></section><section class="about-body"><div class="about-left"><span>AN INTRODUCTION</span><div class="about-figure">w<span>↗</span></div></div><div><h2>Hi.</h2><p>I'm a first-year CS student learning by building real projects and revising them in public.</p><p>This notebook holds the actual decisions, tradeoffs and useful mistakes behind the work: what got tried, what broke, and what the next version learned. Posted as the work happens.</p><a class="read-link" href="#archive">READ THE NOTES <span>↗</span></a></div></section>`)}
function render(keep=false){let route=decodeURIComponent(location.hash.slice(1)||'home');app.innerHTML=route==='archive'?archive():route==='about'?about():route===`essay/${p.id}`?article():home();document.querySelectorAll('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===(route.startsWith('essay')?'archive':route)));let input=document.querySelector('#search');input?.addEventListener('input',e=>{let pos=e.target.selectionStart;query=e.target.value;render(true);let next=document.querySelector('#search');next.focus();next.setSelectionRange(pos,pos)});if(!keep){window.scrollTo(0,0)}progress()}
function progress(){let bar=document.querySelector('#read-progress');if(bar){let h=document.documentElement;bar.style.width=(h.scrollTop/(h.scrollHeight-h.clientHeight)*100||0)+'%'}}
window.addEventListener('hashchange',()=>render());window.addEventListener('scroll',progress,{passive:true});render();loadRemote();
